name: OIDC Terraform Deploy Test

on:
  workflow_dispatch:  # allows manual execution
#   push:
#     branches: [main] # allows push to main to trigger workflow

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-deploy-role
          aws-region: eu-west-1

      - name: Terraform Init
        run: cd oidc-ci/deploy && terraform init

      - name: Terraform Plan
        run: cd oidc-ci/deploy && terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: cd oidc-ci/deploy && terraform apply -auto-approve